import { IAccountMeta } from "./AccountMeta";
import { AccountType } from "./AccountType";
import { IAttachment } from "./Attachment";
import { ILocation } from "./Location";
import { INote } from "./Note";
import { IObjectGroup } from "./ObjectGroup";
import { IPiggyBank } from "./PiggyBank";
import { IUser } from "./User";

export interface IAccount {
  id: number;
  created_at?: Date;
  updated_at?: Date;
  deleted_at?: Date;
  uesr_id: number;
  account_type_id: number;
  name: string;
  virtual_balance?: string;
  iban?: string;
  active: boolean;
  encrypted: boolean;
  order: number;
  accountMeta: IAccountMeta[];
  account_meta_count?: number;
  accountType: AccountType;
  attachments: IAttachment[];
  account_number: string;
  edit_name: string;
  locations: ILocation[];
  notes: INote[];
  objectGroups: IObjectGroup[];
  piggyBanks: IPiggyBank[];
  transactions: ITransaction[];
  user: IUser;
  lastActivityDate: Date;
  startBalance: string;
  endBalance: string;
  difference: string;
  interest: string;
  interestPeriod: string;
  accountTypeString: string;
  location: string;
  loability_direction: string;
  current_debt: string;
  user_group_id?: number;
}
